version: 2

jobs:
  build:
    working_directory: ~/repo
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: Build Docker images
          command: docker-compose up -d --build
      - run:
          name: Lint the user service
          command: docker-compose exec users flake8 project
      - run:
          name: Lint the user service
          command: docker-compose exec users python manage.py test
