version: 2

jobs:
  build:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    working_directory: ~/repo
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose.yml build
      - run:
          name: Spin up Docker containers
          command: docker-compose -f docker-compose.yml up -d
      - run:
          name: Lint the user service
          command: docker-compose -f docker-compose.yml run users flake8 project
      - run:
          name: Test the user service
          command: docker-compose -f docker-compose.yml run users python manage.py test
