version: 2

jobs:
  build:
    docker:
      - image: docker:17.03.2-ce-git
    working_directory: ~/repo
    # environment:
    #   - NODE_ENV: test
    #   - REACT_APP_USERS_SERVICE_URL: http://localhost:3000
    #   - REACT_APP_MOVIES_SERVICE_URL: http://localhost:3001
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              bash \
              jq \
              curl \
              nodejs
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose.yml build
      - run:
          name: Spin up Docker containers
          command: docker-compose -f docker-compose.yml up -d
      - run:
          name: Test the user service
          command: docker-compose -f docker-compose.yml run users python manage.py test
      # - run:
      #     name: Test the movies service
      #     command: docker-compose -f docker-compose.yml run movies-service-review npm test
